name: pdi-topics
channels:
- conda-forge
dependencies:
- python=3.7
- scikit-learn
- bokeh
- numpy
- nltk
- jupyterlab=3
- gensim
- scattertext
- pandas
- spacy
- elasticsearch
- elasticsearch-dsl
- pdfminer.six
- wordcloud
- matplotlib
- line_profiler
- pillow=4.3.0
- pyldavis
